export {
  type AttendanceSession,
  type AttendanceRecord,
  type StudentAttendanceRecord,
  type AttendanceStatus,
  type SessionStatus,
  type CreateSessionInput,
  type UpdateStatusInput,
  type BulkUpdateInput,
  type CheckInInput,
  type CheckInResponse,
  type StudentAttendanceStatistics,
  attendanceSessionSchema,
  attendanceRecordSchema,
  studentAttendanceRecordSchema,
  attendanceStatusSchema,
  sessionStatusSchema,
  createSessionSchema,
  updateStatusSchema,
  bulkUpdateSchema,
  checkInSchema,
  checkInResponseSchema,
  studentAttendanceStatisticsSchema,
} from './model/schema';

export {
  useAttendanceSessions,
  useAttendanceSession,
  useCreateSession,
  useCloseSession,
  useRegenerateCode,
  useDeleteSession,
  useAttendanceRecords,
  useUpdateAttendanceStatus,
  useBulkUpdateAttendance,
  useCheckIn,
  useStudentAttendanceRecords,
  useStudentAttendanceStatistics,
} from './api/queries';
